-- Example code to run this file:
-- use mlua::Lua;
-- let lua_code = match fs::read_to_string("lua/parse.lua") {
--     Ok(str) => str,
--     Err(_) => {
--         println!("\x1b[31mTindy cannot run without the neccesary lua scripts, ensure they are in the same directory as the executable.");
--         String::new()
--     }
-- };
--
-- let lua = Lua::new();
-- let _ = lua.load(&lua_code).exec();

